### ISSUE TITLE
How to run examples like on https://magicleaphelio.com/devsamples/

### ISSUE THREAD

**Issue by netgfx** [magicleap/prismatic#1]
I keep getting the error: 
```
Uncaught ReferenceError: mlWorld is not defined
    at HTMLElement.render (prismatic.min.js:1)
    at HTMLElement.attributeChangedCallback (prismatic.min.js:1)
```
When trying to run the intermediate sample from here: https://developer.magicleap.com/learn/guides/prismatic-positioning-quads-and-scrollable-content

Or any of the samples from this repo.

**Comment by chrisdubya** [comment]
hey @netgfx are you trying to run this in Helio on a Magic Leap device or through another browser?

**Comment by netgfx** [comment]
On Chrome (from what I gather, this isn't possible right?). If there is another way to test without the headset on (developer hub maybe?) please do tell.

**Comment by chrisdubya** [comment]
Right, at the moment, it's only possible to render and view 3D content with Prismatic through Helio.  

You can, however, use the `alt-image` attribute to fallback to a specified flat image when viewing on another browser.  There's an example of this here: https://glitch.com/edit/#!/hello-prismatic?path=index.html:20:6

 `alt-image` documentation [here](https://magicleaphelio.com/WebAPI/docs/prismatic-ml-model.html#alt-img)

**Comment by netgfx** [comment]
Thanks really helpful! Which is the right channel to ask questions about Prismatic/Helio browser etc, stackoverflow / github via issues / or somewhere else?

**Comment by chrisdubya** [comment]
Np! For anything Prismatic related, I would file an issue here.  If it's related to the Helio Browser specifically, I would post on [magic leap's developer forum](https://forum.magicleap.com/)

**Comment by netgfx** [comment]
Thanks appreciate the help!
