### ISSUE TITLE
On latest lumin version browserWidth is not a function

### ISSUE THREAD

**Issue by netgfx** [magicleap/prismatic#2]
Hello, I downloaded latest lumin OS for Magic Leap and I had the code described here: https://magicleaphelio.com/WebAPI/docs/prism-size.html

But js console threw error that `browserWidth, browserHeight, browserBreadth` are not functions, and indeed changing them to:
```
var width = window.mlWorld.browserWidth;
var height = window.mlWorld.browserHeight;
var breadth = window.mlWorld.browserBreadth;
```
works without problems. Maybe documentation should be updated?

**Comment by chrisdubya** [comment]
Hey, @netgfx thanks for catching that, we've updated the API docs to reflect that: https://magicleaphelio.com/WebAPI/docs/prism-size.html
